### ISSUE TITLE
[🐛] Broken interstitials

### ISSUE THREAD

**Issue by dylancom** [invertase/react-native-google-ads#16]
`undefined is not an object (evaluating 'module.app.name')` pops up when trying to use interstitials (and probably rewarded ads).

I think this is related to how the default export is now the GoogleAdsModule directly, which used to be a function call to `createNameSpace(args)`, containing all the native module names etc.

Original: https://github.com/invertase/react-native-firebase/blob/v11.5.0/packages/admob/lib/index.js#L79
Now: https://github.com/invertase/react-native-google-ads/blob/main/lib/index.js#L50

**Comment by mikehardy** [comment]
Probably yes - this one is a little tricky
react-native-firebase is a monorepo with multiple native modules in different packages and some in the same package, and includes module loading infrastructure for all of them.
Not a monorepo here but still multiple native modules, and I intended to port the module loading infrastructure over (and genericize it a bit, because we need the same for MLKit which is also on the "extracted to new repository, not working yet" project list)

Clearly something not working right in the multiple-native-module-loading infra then - this stuff is pretty subtle unfortunately and I don't work with it much, so when I *do* have to go in there I basically light the whole thing up with println debugging and just slowly trace through for a fix. A bit tedious but at least once it works it really works
